services:
  forecast-app:
    container_name: financial_tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./client_secret.json:/app/client_secret.json
      - ./output:/app/output
      - ./logs:/app/logs
      - ./backups:/app/backups
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    # restart: unless-stopped