services:
  forecast-app:
    container_name: financial_tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    volumes:
        - ./client_secret.json:/app/client_secret.json
        - ./po_database.db:/app/po_database.db
        - ./output:/app/output
        - ./forecast_output.csv:/app/forecast_output.csv
        - ./forecast_pivot.xlsx:/app/forecast_pivot.xlsx
    #   - ./logs:/app/logs
    # restart: unless-stopped