logger:
  name: forecast_logger
  level: INFO
  log_dir: logs
  file_name: forecast.log
  handlers:
    console:
      enabled: true
      level: WARNING
    file:
      enabled: true
      level: INFO
      rotating: true
      maxBytes: 1048576
      backupCount: 3
  format:
    pattern: '[%(asctime)s] [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'