logger:
  name: invoice_app
  level: INFO

  log_dir: logs
  file_name: system.log

  handlers:
    console:
      enabled: true
      level: INFO

    file:
      enabled: true
      level: INFO
      rotating: true         # Enable rotating file handler
      maxBytes: 5242880      # 5MB per log file
      backupCount: 2         # Keep 2 log files in rotation

  format:
    pattern: "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
