logger:
  name: invoice_app
  level: INFO

  log_dir: logs
  file_name: system.log

  handlers:
    console:
      enabled: true
      level: INFO

    file:
      enabled: true
      level: INFO
      max_bytes: 5000000   # 5 MB
      backup_count: 3

  format:
    pattern: "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
